//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.payment_servic = new HashSet<payment_servic>();
            this.per_servic_order = new HashSet<per_servic_order>();
        }
    
        public int id { get; set; }
        public System.DateTime creation_date { get; set; }
        public Nullable<int> status_order { get; set; }
        public Nullable<int> status_servic { get; set; }
        public int execution_time_day_ { get; set; }
    
        public virtual status_order status_order1 { get; set; }
        public virtual status_servic status_servic1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment_servic> payment_servic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<per_servic_order> per_servic_order { get; set; }
    }
}
