//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class performed_service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public performed_service()
        {
            this.service_order = new HashSet<service_order>();
        }
    
        public int id { get; set; }
        public int service_id { get; set; }
        public System.DateTime execution_date { get; set; }
        public int executor_id { get; set; }
        public int analyzer_id { get; set; }
        public int patient_id { get; set; }
        public string result { get; set; }
    
        public virtual user user { get; set; }
        public virtual work_analyzer work_analyzer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<service_order> service_order { get; set; }
    }
}
