//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class work_analyzer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public work_analyzer()
        {
            this.performed_service = new HashSet<performed_service>();
        }

		public work_analyzer(int maxIdWork, int id1, DateTime now, TimeSpan timeSpan, int v1, int id2, string v2)
		{
			MaxIdWork=maxIdWork;
			Id1=id1;
			Now=now;
			TimeSpan=timeSpan;
			V1=v1;
			Id2=id2;
			V2=v2;
		}

		public int id { get; set; }
        public Nullable<int> analyzer_id { get; set; }
        public System.DateTime order_received_date { get; set; }
        public System.TimeSpan order_received_time { get; set; }
        public long order_execution_time_sec_ { get; set; }
        public Nullable<int> service_id { get; set; }
        public Nullable<int> result { get; set; }
        public string status { get; set; }
    
        public virtual analyzer analyzer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<performed_service> performed_service { get; set; }
        public virtual service service { get; set; }
		public int MaxIdWork { get; }
		public int Id1 { get; }
		public DateTime Now { get; }
		public TimeSpan TimeSpan { get; }
		public int V1 { get; }
		public int Id2 { get; }
		public string V2 { get; }
	}
}
