//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class performed_service
    {
        public int id { get; set; }
        public int service_id { get; set; }
        public System.DateTime execution_date { get; set; }
        public int executor_id { get; set; }
        public int analyzer_id { get; set; }
        public int patient_id { get; set; }
        public string result { get; set; }
    
        public virtual service service { get; set; }
        public virtual user user { get; set; }
        public virtual work_analyzer work_analyzer { get; set; }
    }
}
